name: Build and deploy ASP.Net Core app to Azure Web App - financetracker-be

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: financetracker-be
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: FinanceTracker.API
  PUBLISH_DIR: publish

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Inject MongoDB connection string
        shell: pwsh
        run: |
          $jsonPath = "${{ env.PROJECT_PATH }}/appsettings.json"
          $json = Get-Content $jsonPath | ConvertFrom-Json
          $json.MongoDbSettings.ConnectionString = "${{ secrets.MONGO_DB_CONNECTION_STRING }}"
          $json | ConvertTo-Json -Depth 10 | Set-Content $jsonPath

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_DIR }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_057095CE70EA489A8A382184A5381010 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1893625963B749CD907DB803B36EA9CF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8D1896F87E4644D1BE0298774F1BF5E9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PUBLISH_DIR }}
